//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Marketplace.Repositorios.SqlServer.DbFirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cartao
    {
        public int Id { get; set; }
        public int IdCliente { get; set; }
        public System.Guid Guid { get; set; }
        public string Mascara { get; set; }
        public string Apelido { get; set; }
    
        public virtual Cliente Cliente { get; set; }
    }
}
